_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 77
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
